version: '3.5'

networks:
  backend:
    driver: ${NETWORKS_DRIVER}
    
volumes:
  mysql:
    driver: ${VOLUMES_DRIVER}
  
services:

### PHP Worker ############################################
    php-worker:
      build:
        context: ./php-worker
        args:
          - PHP_VERSION=${PHP_VERSION}
          - PUID=${PHP_WORKER_PUID}
          - PGID=${PHP_WORKER_PGID}
      image: laradock-worker/php-worker
      volumes:
        - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
        - ./php-worker/supervisord.d:/etc/supervisord.d
      environment:
        - TZ=${WORKSPACE_TIMEZONE}
      depends_on:
        - mariadb-php-worker
      networks:
        - backend

### MariaDB ##############################################
    mariadb-php-worker:
      build:
        context: ./mariadb
        args:
          - MARIADB_VERSION=${MARIADB_VERSION}
      environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - TZ=${WORKSPACE_TIMEZONE}
      volumes:
        - ${DATA_PATH_HOST}/mariadb:/var/lib/mysql:delegated
      networks:
        - backend
### Composer ############################################
    composer-php-worker:
      build:
        context: ./composer
      image: laradock-worker/php-worker-composer
      command: install
      working_dir: ${APP_CODE_PATH_CONTAINER}
      depends_on:
        - php-worker
      volumes: 
        - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
